#!/bin/bash

emcc -O2 -s EMULATE_FUNCTION_POINTER_CASTS=1 -s USE_ZLIB=1 \
	--memory-init-file 0 \
	./build/xmllint.o ./build/.libs/libxml2.a \
	-o xmllint.raw.js --pre-js ./src/pre.js

sed '/\/\* XMLLINT.RAW.JS \*\// {
	r ./xmllint.raw.js
	d
}' < ./src/wrapper.js > ./xmllint.js

rm -rf xmllint.raw.js
